// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDRIOD_API_KEY']!,
    appId: '1:956355807440:android:f7901b2a10a6935f5676d5',
    messagingSenderId: '956355807440',
    projectId: 'recychamp',
    storageBucket: 'recychamp.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:956355807440:ios:6d8b0255efdc01485676d5',
    messagingSenderId: '956355807440',
    projectId: 'recychamp',
    storageBucket: 'recychamp.appspot.com',
    iosBundleId: 'com.y311.recychamp',
  );
}
